#!/bin/bash

ip netns add ns1
ip netns add ns2
ip link add name veth1 type veth peer name veth2
ip link set dev veth1 netns ns1
ip link set dev veth2 netns ns2

ip netns exec ns1 ip link set lo up
ip netns exec ns1 ip link set veth1 up
ip netns exec ns1 ip addr add 10.1.1.1/24 dev veth1
ip netns exec ns1 ip route add 224.0.0.0/4 dev veth1

ip netns exec ns2 ip link set lo up
ip netns exec ns2 ip link set veth2 up
ip netns exec ns2 ip addr add 10.1.1.2/24 dev veth2
ip netns exec ns2 ip route add 224.0.0.0/4 dev veth2



